### ISSUE TITLE
链接打不开了

### ISSUE THREAD

**Issue by haobing55** [ritajie/incomplete-projects#8]
辛苦作者了！！怎么打不开了？

**Comment by ritajie** [comment]
非常非常抱歉😭，9月8号被请喝茶了，说会帮助境外势力攻击中国，要求我把网站关闭了。

你看到的应该是这个页面：
>因技术问题，本站已下线。
>
>2022年9月8日

**Comment by zhucebulehututu** [comment]
我正准备写个类似的，没想到找到你这了。

**Comment by fushui-Fang** [comment]
我觉得只要信息公开可查，那就是中国现实情况，那就是需要解决的具体问题，还担心境外势力攻击？真的是越活越回去了，当鸵鸟是吧

**Comment by ritajie** [comment]
@fushui-Fang 政府的逻辑是这样的：

1. 这些数据虽然是真实的，但通常查询难度大
2. 将这些信息汇总起来，降低了查询难度
3. 由于查询难度降低，不怀好意的境外势力更容易据此作文章

其实这逻辑也可以理解 😹

**Comment by cmdxyy123456** [comment]
呜呜呜，现在做研究需要这个数据，想问问作者能不能私发呢，幸苦了

**Comment by ritajie** [comment]
> 呜呜呜，现在做研究需要这个数据，想问问作者能不能私发呢，幸苦了

本项目只做了数据**可视化**，其实所有数据都来自这个仓库：https://github.com/WeNeedHome/SummaryOfLoanSuspension

**Comment by cmdxyy123456** [comment]
> > 呜呜呜，现在做研究需要这个数据，想问问作者能不能私发呢，幸苦了
> 
> @cmdxyy123456 本项目只做了数据**可视化**，其实所有数据都来自这个仓库：https://github.com/WeNeedHome/SummaryOfLoanSuspension

>感谢!

**Comment by fushui-Fang** [comment]
> @fushui-Fang 政府的逻辑是这样的：
> 
> 1. 这些数据虽然是真实的，但通常查询难度大
> 2. 将这些信息汇总起来，降低了查询难度
> 3. 由于查询难度降低，不怀好意的境外势力更容易据此作文章
> 
> 其实这逻辑也可以理解 😹

你这个逻辑看着不成立啊，我们可以搜到难道境外势力搜不到嘛，感觉列出来帮助后续的人避免踩雷不是更重要一点嘛

**Comment by fushui-Fang** [comment]
而且感觉还可以直接编造更大的数据，<手动狗头>

**Comment by steelxiang** [comment]
> 非常非常抱歉😭，9月8号被请喝茶了，说会帮助境外势力攻击中国，要求我把网站关闭了。
> 
> 你看到的应该是这个页面：
> 
> > 因技术问题，本站已下线。
> > 2022年9月8日

这理由也太牵强了，如果不配合会怎么样呢

**Comment by zfyzmh** [comment]
> > 非常非常抱歉😭，9月8号被请喝茶了，说会帮助境外势力攻击中国，要求我把网站关闭了。
> > 你看到的应该是这个页面：
> > > 因技术问题，本站已下线。
> > > 2022年9月8日
> 
> 这理由也太牵强了，如果不配合会怎么样呢

寻衅滋事

**Comment by DarnedBuzzard70** [comment]
《说会帮助境外势力攻击中国》

**Comment by ghost** [comment]
不是大哥，你都打算干这事了，还备案？找死啊！
难不成你还相信特色？
不要怕被墙，墙全是bug，除非他全部IP黑洞，基本上只对大网站生效，CDN都不敢封。特色面临的选择其实是断绝与国际互联网交流与

**Comment by sdy623** [comment]
可以拿卡了吧
